S1:
	hostname: 192.168.255.70
	port: 22
	username: josh
	password: cisco
	platform: ios
	groups:
		virtual_switches

S2:
	hostname: 192.168.255.72
	port:22
	username: josh
	password: cisco
	platform: ios
	groups:
		virtual_switches

S3:
	hostname: 192.168.255.82
	port:22
	usernam: josh
	password: cisco
	platform: ios
	groups:
		virtual_switches

S4:
	hostname: 192.168.255.83
	port:22
	usernam: josh
	password: cisco
	platform: nxos
	groups:
		virtual_switches

S5:
	hostname: 192.168.255.84
	port:22
	usernam: josh
	password: cisco
	platform: ios
	groups:
		virtual_switches

S6:
	hostname: 192.168.255.85
	port:22
	usernam: josh
	password: cisco
	platform: ios
	groups:
		virtual_switches

R1:
	hostname: 192.168.255.1
	port:22
	usernam: josh
	password: cisco
	platform: ios
	groups:
		virtual_router
