XE-1:
	hostname: 172.16.102.136
	port: 22
	username: cisco
	password: cisco
	platform: ios
	groups:
		- xe-routers

XR-3:
	hostname: 172.16.102.138
	port:22
	username: genie
	password: sonpari
	platform: iosxr
	groups:
		- xr-routers

NX-2:
	hostname: 172.16.102.137
	port:443
	usernam: admin
	password: admin
	platform: nxos
	groups: 
		- nx-routers

